spring:
  application:
    name: MOVIES-CONTENT-SERVICE
  docker:
    compose:
      lifecycle-management: start_only
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:8900/mydatabase"
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8750/realms/master"

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8080/eureka"

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
